/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee;
import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;

/**
 *
 * @author Naowas
 */
public class Emprecord extends javax.swing.JFrame {
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    


    /**
     * Creates new form emprecord
     */
    public Emprecord() {
        initComponents();
        conn=db.dbconn();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        empid.setEnabled(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empid = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_add2 = new javax.swing.JTextField();
        txt_job = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txt_doj = new javax.swing.JTextField();
        txt_design = new javax.swing.JTextField();
        txt_dep = new javax.swing.JTextField();
        txt_pc = new javax.swing.JTextField();
        txt_apt = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        record_btn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        radio_male = new javax.swing.JRadioButton();
        radio_female = new javax.swing.JRadioButton();
        btn_clear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_return = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Management System");
        setMaximumSize(new java.awt.Dimension(738, 540));
        setMinimumSize(new java.awt.Dimension(738, 540));
        setPreferredSize(new java.awt.Dimension(820, 540));
        getContentPane().setLayout(null);

        empid.setForeground(new java.awt.Color(255, 0, 0));
        empid.setText("Genarate auto");
        empid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empidActionPerformed(evt);
            }
        });
        getContentPane().add(empid);
        empid.setBounds(180, 70, 107, 30);
        getContentPane().add(txt_firstname);
        txt_firstname.setBounds(180, 110, 107, 30);

        txt_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_surnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_surname);
        txt_surname.setBounds(180, 150, 106, 30);
        getContentPane().add(txt_dob);
        txt_dob.setBounds(180, 220, 107, 30);
        getContentPane().add(txt_email);
        txt_email.setBounds(180, 260, 107, 30);
        getContentPane().add(txt_tel);
        txt_tel.setBounds(180, 300, 107, 30);

        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        getContentPane().add(txt_address);
        txt_address.setBounds(180, 340, 107, 30);
        getContentPane().add(txt_add2);
        txt_add2.setBounds(180, 380, 107, 30);
        getContentPane().add(txt_job);
        txt_job.setBounds(430, 320, 107, 30);

        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(txt_salary);
        txt_salary.setBounds(430, 280, 107, 30);

        txt_doj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dojActionPerformed(evt);
            }
        });
        getContentPane().add(txt_doj);
        txt_doj.setBounds(430, 240, 107, 30);
        getContentPane().add(txt_design);
        txt_design.setBounds(430, 200, 107, 30);
        getContentPane().add(txt_dep);
        txt_dep.setBounds(430, 160, 107, 30);
        getContentPane().add(txt_pc);
        txt_pc.setBounds(430, 120, 107, 30);
        getContentPane().add(txt_apt);
        txt_apt.setBounds(430, 80, 107, 30);
        getContentPane().add(txt_status);
        txt_status.setBounds(430, 360, 107, 30);

        jLabel1.setText("Employee ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 70, 90, 30);

        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 110, 80, 30);

        jLabel3.setText("Surname:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 150, 70, 30);

        jLabel4.setText("Date of birth:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 220, 90, 30);

        jLabel5.setText("Email:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 260, 70, 30);

        jLabel6.setText("Contact:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 300, 70, 30);

        jLabel7.setText("Address 1:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 340, 80, 30);

        jLabel8.setText("Address 2:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 380, 80, 30);

        jLabel9.setText("House no:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 80, 70, 30);

        jLabel10.setText("Post code:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 120, 70, 30);

        jLabel11.setText("Status:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 360, 60, 30);

        jLabel12.setText("Department:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(350, 160, 80, 30);

        jLabel13.setText("Designation:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(350, 200, 80, 30);

        jLabel14.setText("Date hired:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(360, 250, 70, 30);

        jLabel15.setText("Basic salary:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 280, 80, 30);

        jLabel16.setText("Job title:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(370, 320, 60, 30);

        record_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/user.png"))); // NOI18N
        record_btn.setText("Add");
        record_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        record_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                record_btnActionPerformed(evt);
            }
        });
        getContentPane().add(record_btn);
        record_btn.setBounds(470, 420, 120, 40);

        jLabel17.setText("Gender:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(120, 190, 50, 20);

        radio_male.setText("Male");
        radio_male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_maleActionPerformed(evt);
            }
        });
        getContentPane().add(radio_male);
        radio_male.setBounds(170, 190, 60, 23);

        radio_female.setText("Female");
        radio_female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_femaleActionPerformed(evt);
            }
        });
        getContentPane().add(radio_female);
        radio_female.setBounds(230, 190, 66, 23);

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/Reset.png"))); // NOI18N
        btn_clear.setText("Reset");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear);
        btn_clear.setBounds(610, 420, 110, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        jPanel1.add(img);
        img.setBounds(0, 0, 130, 130);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Photo here");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 50, 90, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(590, 40, 130, 130);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/attcah 2.png"))); // NOI18N
        jButton1.setText("Attach photo");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 180, 160, 30);

        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/back.png"))); // NOI18N
        btn_return.setText("Return");
        btn_return.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_return);
        btn_return.setBounds(50, 420, 120, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/users-icon.png"))); // NOI18N
        jLabel18.setText("Employee management System");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(0, 0, 360, 60);

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/logoff.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel2.add(btn_logout);
        btn_logout.setBounds(670, 10, 110, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 850, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_surnameActionPerformed

    private void record_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_record_btnActionPerformed
        // TODO add your handling code here:
        
        try { 
            String sql ="insert into employee_info " 
                    + "(first_name,surname,Dob,Email," 
                    + "Telephone,Address,Department," 
                    + "Image,Salary,Gender,Address2," 
                    + "Post_code, Designation,Status,job_title,Apartment,Date_hired) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
            
            
            pst=conn.prepareStatement(sql); 
            pst.setString(1,txt_firstname.getText());
            pst.setString(2,txt_surname.getText()); 
            pst.setString(3,txt_dob.getText()); 
            pst.setString(4,txt_email.getText()); 
            pst.setString(5,txt_tel.getText()); 
            pst.setString(6,txt_address.getText()); 
            pst.setString(7,txt_dep.getText()); 
            pst.setBytes (8,person_image); 
            pst.setString(9,txt_salary.getText()); 
            pst.setString(10,gender); 
            pst.setString(11,txt_add2.getText()); 
            pst.setString(12,txt_pc.getText()); 
            pst.setString(13,txt_design.getText()); 
            pst.setString(14,txt_status.getText()); 
            pst.setString(15,txt_job.getText()); 
            pst.setString(16,txt_apt.getText()); 
            pst.setString(17,txt_doj.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is saved successfully");    
            
        }
        catch (Exception e){ 
            //JOptionPane.showMessageDialog(null,e);
        }
        
         finally { 
            try{ rs.close(); 
            pst.close(); 
            } 
            catch(Exception e){
                //JOptionPane.showMessageDialog(null,e);
            } 
        }
        
        
        
    }//GEN-LAST:event_record_btnActionPerformed

    private void radio_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_maleActionPerformed
        // TODO add your handling code here:
         gender = "Male";
        radio_male.setSelected(true);
        radio_female.setSelected(false);
        
    }//GEN-LAST:event_radio_maleActionPerformed

    private void radio_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_femaleActionPerformed
        // TODO add your handling code here:
         gender = "Female";
        radio_female.setSelected(true);
        radio_male.setSelected(false);
    }//GEN-LAST:event_radio_femaleActionPerformed

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        
        empid.setText(""); 
        txt_firstname.setText("");
        txt_surname.setText(""); 
        txt_tel.setText("");
        txt_dob.setText("");
        txt_email.setText("");
        txt_address.setText("");
        txt_dep.setText("");
        txt_status.setText("");
        txt_salary.setText(""); 
        txt_add2.setText(""); 
        txt_pc.setText(""); 
        txt_job.setText("");
        txt_apt.setText(""); 
        txt_doj.setText("");
        txt_design.setText("");
        img.setIcon(null);
       
        
        
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void empidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empidActionPerformed
        // TODO add your handling code here:
       empid.setEditable(false);
    }//GEN-LAST:event_empidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        filename =f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
      try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream (image);
            ByteArrayOutputStream bos= new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int readNum; (readNum=fis.read(buf))!=-1; ){

                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_dojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dojActionPerformed

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
                mainpage back=new mainpage();
                back.setVisible(true);
                this.dispose();
        
        
        
        
    }//GEN-LAST:event_btn_returnActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:

        login log=new login();
        log.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_return;
    private javax.swing.JTextField empid;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radio_female;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JButton record_btn;
    private javax.swing.JTextField txt_add2;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_apt;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_design;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_pc;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
    private String gender;
    private ImageIcon format=null;
    String filename=null;
    byte[] person_image=null;
}
