/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.*;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author Naowas
 */
public class Empsearch extends javax.swing.JFrame {
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    


    /**
     * Creates new form emprecord
     */
    public Empsearch() {
        initComponents();
        conn=db.dbconn();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        empid.setEnabled(false);
        txt_firstname.setEditable(false);
        txt_dob.setEditable(false);
        txt_salary.setEditable(false);
        txt_email.setEditable(false);
        txt_surname.setEditable(false);
        txt_address.setEditable(false);
        txt_add2.setEditable(false);
        txt_tel.setEditable(false);
        txt_dep.setEditable(false);
        txt_doj.setEditable(false);
        txt_pc.setEditable(false);
        txt_apt.setEditable(false);
        txt_gender.setEditable(false);
        txt_job.setEditable(false);
        txt_design.setEditable(false);
        txt_status.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empid = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_add2 = new javax.swing.JTextField();
        txt_job = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txt_doj = new javax.swing.JTextField();
        txt_design = new javax.swing.JTextField();
        txt_dep = new javax.swing.JTextField();
        txt_pc = new javax.swing.JTextField();
        txt_apt = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        image_srch = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        txt_gender = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_show = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Management System");
        setMinimumSize(new java.awt.Dimension(800, 550));
        setPreferredSize(new java.awt.Dimension(800, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        empid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empidActionPerformed(evt);
            }
        });
        getContentPane().add(empid);
        empid.setBounds(180, 80, 107, 26);
        getContentPane().add(txt_firstname);
        txt_firstname.setBounds(180, 120, 107, 30);

        txt_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_surnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_surname);
        txt_surname.setBounds(180, 160, 106, 30);
        getContentPane().add(txt_dob);
        txt_dob.setBounds(180, 240, 107, 29);
        getContentPane().add(txt_email);
        txt_email.setBounds(180, 280, 107, 30);
        getContentPane().add(txt_tel);
        txt_tel.setBounds(180, 320, 107, 30);

        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        getContentPane().add(txt_address);
        txt_address.setBounds(180, 360, 107, 30);
        getContentPane().add(txt_add2);
        txt_add2.setBounds(180, 400, 107, 30);
        getContentPane().add(txt_job);
        txt_job.setBounds(410, 320, 107, 30);

        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(txt_salary);
        txt_salary.setBounds(410, 280, 107, 30);
        getContentPane().add(txt_doj);
        txt_doj.setBounds(410, 240, 107, 30);
        getContentPane().add(txt_design);
        txt_design.setBounds(410, 200, 107, 30);
        getContentPane().add(txt_dep);
        txt_dep.setBounds(410, 160, 107, 30);
        getContentPane().add(txt_pc);
        txt_pc.setBounds(410, 120, 107, 30);
        getContentPane().add(txt_apt);
        txt_apt.setBounds(410, 80, 107, 30);
        getContentPane().add(txt_status);
        txt_status.setBounds(410, 370, 107, 30);

        jLabel1.setText("Employee ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(94, 80, 80, 30);

        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(95, 124, 80, 30);

        jLabel3.setText("Surname:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(106, 160, 70, 30);

        jLabel4.setText("Date of birth:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(95, 244, 80, 20);

        jLabel5.setText("Email:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(118, 280, 50, 30);

        jLabel6.setText("Contact:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(112, 320, 60, 30);

        jLabel7.setText("Address 1:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(102, 360, 70, 30);

        jLabel8.setText("Address 2:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(102, 400, 70, 30);

        jLabel9.setText("House no:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(339, 80, 60, 30);

        jLabel10.setText("Post code:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(331, 120, 70, 30);

        jLabel11.setText("Status:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 374, 60, 30);

        jLabel12.setText("Department:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(321, 160, 80, 30);

        jLabel13.setText("Designation:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(320, 200, 80, 30);

        jLabel14.setText("Date hired:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(334, 244, 70, 30);

        jLabel15.setText("Basic salary:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(330, 284, 70, 30);

        jLabel16.setText("Job title:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(342, 324, 60, 30);

        jLabel17.setText("Gender:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(119, 200, 60, 30);

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/Reset.png"))); // NOI18N
        btn_clear.setText("Reset");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear);
        btn_clear.setBounds(620, 450, 110, 40);

        txt_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_searchMouseExited(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });
        getContentPane().add(txt_search);
        txt_search.setBounds(244, 23, 150, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(image_srch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image_srch, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(590, 50, 117, 129);

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/back.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(50, 450, 100, 41);

        txt_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_genderActionPerformed(evt);
            }
        });
        getContentPane().add(txt_gender);
        txt_gender.setBounds(180, 200, 110, 29);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/search 2.png"))); // NOI18N
        jLabel18.setText("Search by Surname");

        txt_show.setBackground(new java.awt.Color(255, 0, 0));
        txt_show.setForeground(new java.awt.Color(255, 0, 0));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/logoff.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel18)
                .addGap(172, 172, 172)
                .addComponent(txt_show, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_show, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button icons/memo.png"))); // NOI18N
        jButton1.setText("Save As PDF");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 450, 160, 41);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("User Photo");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(610, 180, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_surnameActionPerformed

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        
        empid.setText(""); 
        txt_firstname.setText("");
        txt_surname.setText(""); 
        txt_tel.setText("");
        txt_dob.setText("");
        txt_email.setText("");
        txt_address.setText("");
        txt_dep.setText("");
        txt_status.setText("");
        txt_salary.setText(""); 
        txt_add2.setText(""); 
        txt_pc.setText(""); 
        txt_job.setText("");
        txt_apt.setText(""); 
        txt_doj.setText("");
        txt_design.setText("");
       
        
        
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        // TODO add your handling code here:
            try{ String sql ="select * from employee_info where surname=? ";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            String add1 =rs.getString("id");
            empid.setText(add1);
            String add2 =rs.getString("first_name");
            txt_firstname.setText(add2);
            String add3 =rs.getString("surname");
            txt_surname.setText(add3);
            String add4 =rs.getString("Dob");
            txt_dob.setText(add4);
            String add5 =rs.getString("Email");
            txt_email.setText(add5);
            String add6 =rs.getString("Telephone");
            txt_tel.setText(add6);
            String add7 =rs.getString("Address");
            txt_address.setText(add7);
            String add8 =rs.getString("Department");
            txt_dep.setText(add8);
            String add9 =rs.getString("Gender");
            txt_gender.setText(add9);
            String add10 =rs.getString("Salary");
            txt_salary.setText(add10);
            String add11 =rs.getString("Address2");
            txt_add2.setText(add11);
            String add12 =rs.getString("Apartment");
            txt_apt.setText(add12);
            String add13 =rs.getString("Post_code");
            txt_pc.setText(add13);
            String add14 =rs.getString("Status");
            txt_status.setText(add14);
            String add15 =rs.getString("Date_hired");
            txt_doj.setText(add15);
            String add16 =rs.getString("job_title");
            txt_job.setText(add16);
            String add17 =rs.getString("Designation");
            txt_design.setText(add17);
            byte[] img = rs.getBytes("Image");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(image_srch.getWidth(), image_srch.getHeight(), Image.SCALE_SMOOTH));
                image_srch.setIcon(imageIcon);

        }
        catch(Exception e)
        {
        } finally
        {
            try{
                rs.close();
                pst.close();
            } 
            catch(Exception e)
            {
            }
        }
    }//GEN-LAST:event_txt_searchKeyTyped

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void empidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empidActionPerformed
        // TODO add your handling code here:
       empid.setEditable(false);
    }//GEN-LAST:event_empidActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        mainpage back=new mainpage();
                back.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_genderActionPerformed

    private void txt_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseEntered
        // TODO add your handling code here:
        
        txt_show.setText("Case Sensetive!");
        
    }//GEN-LAST:event_txt_searchMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            String a = txt_firstname.getText();
            String b = txt_surname.getText();
            String c = txt_gender.getText();
            String d = txt_address.getText();
            String e = txt_design.getText();
            String f = txt_salary.getText();
            String g =txt_add2.getText();
            String h=txt_apt.getText();
            String i=txt_email.getText();
            String j = txt_dob.getText();
            String k= txt_doj.getText();
            String l= txt_tel.getText();
            String m=txt_job.getText();
            String n=txt_pc.getText();
            String o =txt_dep.getText();
            String p=txt_status.getText();
            
    
            JFileChooser dialog = new JFileChooser();
            dialog.setSelectedFile(new File(a+"-Details"+".pdf"));
            int dialogResult = dialog.showSaveDialog(null);
            if (dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath = dialog.getSelectedFile().getPath();
           
        try {
            
           
           Document myDocument = new Document();
           PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
           myDocument.open();
           
           myDocument.add(new Paragraph("DETAILS OF EMPLOYEE",FontFactory.getFont(FontFactory.TIMES_BOLDITALIC,20,Font.BOLD )));
           myDocument.add(new Paragraph(new Date().toString()));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add(new Paragraph("*******************************************************************************************"));

           myDocument.add((new Paragraph("EMPLOYEE DETAILS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD))));
           myDocument.add((new Paragraph("Name of Employee: " +a + " "+b,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Gender: "+c,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Date OF Birth: "+j,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Email: "+i,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Phone No: "+l,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Address Line 1: "+d,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Address Line 2: "+g,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("House No: "+h,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Postal Code: "+n,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Department: "+o,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Designation: "+e,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Date of Hire: "+k,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Basic Salary: "+f,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Job Title: "+m,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Current Status: "+p,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add((new Paragraph("Salary: "+f,FontFactory.getFont(FontFactory.TIMES_ROMAN,13,Font.PLAIN))));
           myDocument.add(new Paragraph("*******************************************************************************************"));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
        
           
           
           myDocument.newPage();
           myDocument.close();  
           JOptionPane.showMessageDialog(null,"Report was successfully generated");
           
     }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
         
         
     }
     finally {
            
            try{
               rs.close();
               pst.close();
                
            }
            catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
         
            }
     }
   }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseExited
        // TODO add your handling code here:
        
        txt_show.setText("");
    }//GEN-LAST:event_txt_searchMouseExited

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:

        login log=new login();
        log.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empsearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_logout;
    private javax.swing.JTextField empid;
    private javax.swing.JLabel image_srch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_add2;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_apt;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_design;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_pc;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel txt_show;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
    
}
